name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Pkgs
      run: sudo apt-get update
    - name: Install Deps
      run: sudo apt-get install gcc g++ make 
  
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Pkgs
      run: brew update

    - name: Check pkgs
      run: brew info gcc g++ make
      
    - name: Install Deps
      run: brew install gcc g++ make
