name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update Pkgs
      run: sudo apt-get update

    - name: Install Deps
      run: sudo apt-get install gcc g++ make 

    - name: check gcc version
      run: gcc --version
  
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Pkgs
      run: brew update

    - name: check gcc version
      run: gcc --version